#!/bin/sh

echo "pre-commit: run \033[33mmvn clean package\033[0m."
mvn clean package

RESULT=$?

if [ $RESULT -ne 0 ];then
    echo ""
    echo "\033[31mrun mvn clean package failure.\033[0m"
fi

exit $RESULT